import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layouts/Navbar";
import GlobalProvider from "./GlobalProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <GlobalProvider>
      <Nav/>
      {children}
      </GlobalProvider></body>

    </html>
  );
}